server:
  port: 80 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-gateway # 服务名
  cloud:
    nacos: # nacos配置
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway: # gateway配置
      discovery:
        locator:
          enabled: true  # gateway可以发现nacos中的微服务，并自动生成转发路由
      routes: # 路由配置
        - id: service-core
          uri: lb://service-core # lb（Load Balancer，负载均衡器）
          predicates:
            - Path=/*/core/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**

