server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  redis: # redis
    host: localhost
    port: 6379
    database: 0
    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud: # nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq: # rabbitmq配置
    host: localhost
    port: 5672
    virtual-host: /srbhost
    username: srbuser
    password: srbuser

# feign
feign:
  client:
    config:
      default:
        # openfeign默认的连接超时时间为1秒，测试时很可能会出现远程调用超时错误。
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel: # 开启Feign对Sentinel的支持
    enabled: true

# 指定监控的接口，以及日志级别
logging:
  level:
    xyz.funnyboy.srb.sms.client.CoreUserInfoClient: DEBUG

# 阿里云短信
aliyun:
  sms:
    region-id: cn-shanghai
    key-id: LTAI5tDvGrZiZ44Zcvp9kYzV
    key-secret: gSrbXmTmELbSdWEoYXvu4UttATc18x
    template-code: SMS_154950909
    sign-name: 阿里云短信测试
